import './globals.css'
import { Inter } from 'next/font/google'

// The top-most layout is called the Root Layout. This required layout is shared across all 
// pages in an application. Root layouts must contain html and body tags.

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
